version: '3.7'

services: 
  app-service:
    image: juliuskrah/cdcapp:1.0
    container_name: cdc-service
    depends_on: 
    - postgres
    environment: 
    - POSTGRES_REACTIVE_CLIENT_HOST=postgres
    - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    - MICRONAUT_SERVER_CORS_ENABLED=true
    ports:
    - '8082:8082'
  app-client:
    image: louisga/cdc-client:1.0
    container_name: cdc-client
    depends_on:
    - app-service
    environment:
    - USERS_URL=http://app-service:8082/api/users
    - EVENTS_STREAMING_URL=http://localhost:8082/api/users/stream
    - SERVER_SERVLET_CONTEXT_PATH=/
    ports:
    - '8081:8081'
  postgres:
    image: juliuskrah/postgres:12-alpine-cdc
    container_name: cdc-postgres
    environment: 
    - POSTGRES_PASSWORD=postgrespwd
    volumes: 
    - pgdata:/var/lib/postgresql/data
  keycloak:
    image: juliuskrah/keycloak:8.0.1
    container_name: cdc-keycloak
    depends_on: 
    - postgres
    environment: 
    - KEYCLOAK_USER=test
    - KEYCLOAK_PASSWORD=test    
    - DB_ADDR=postgres
    - DB_PORT=5432
    - DB_DATABASE=sample
    - DB_SCHEMA=sample
    - DB_USER=sample
    - DB_PASSWORD=sample
    ports:
    - '8080:8080'
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.2
    container_name: cdc-zookeeper
    environment: 
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    - ZOOKEEPER_SYNC_LIMIT=2
    volumes: 
    - zk-data:/var/lib/zookeeper/data
    - zk-trx-logs:/var/lib/zookeeper/log
  kafka:
    image: confluentinc/cp-kafka:5.3.2
    container_name: cdc-kraken
    depends_on: 
    - zookeeper
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    - KAFKA_BROKER_ID=1
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes: 
    - kafka-data:/var/lib/kafka/data
  connect:
    image: debezium/connect:1.0.0.Final
    container_name: cdc-connect
    depends_on: 
    - kafka
    - postgres
    environment:
    - BOOTSTRAP_SERVERS=kafka:29092
    - GROUP_ID=1
    - CONFIG_STORAGE_TOPIC=cdc_connect_configs
    - OFFSET_STORAGE_TOPIC=cdc_connect_offsets
    - STATUS_STORAGE_TOPIC=cdc_connect_statuses
    ports: 
    - '8083:8083'

volumes: 
  pgdata:
  zk-data:
  zk-trx-logs:
  kafka-data: